language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
addons:
  sauce_connect:
    username: markogresak
    access_key:
      secure: CRTdvi3eR7D6Dw7QsCJy7hA6xIj1y0cmCODMVku3N5rofiixfV6f35TKuQZ9jujZeUO8PYEGDEWuIwYnBk0Ia+hbH7j0v9xfiBb/kkWIYmO+c/Ux/uw/atOWvSheo0529spZiA+Ov+gyrRnPAONYaJquCn5Lp2XPeM0Shu/9Zg4=
